// OpenWeather API configuration
const config = {
    CESIUM_ACCESS_TOKEN: process.env.REACT_APP_CESIUM_ACCESS_TOKEN || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI0ODczYmEyYy01MTFjLTQ1NmQtYTFiNy0wMmY0NzQ2MmViNTkiLCJpZCI6MjY1MjU2LCJpYXQiOjE3Mzk3MTc2MDd9.e7F3oV9xZEAoHDDlQ_e7ry3thhLkvaUmaKVBw9R3BBU',
    OPENWEATHER_API_KEY: process.env.REACT_APP_OPENWEATHER_API_KEY || '5cf838f25da8c4ea7c02910504ebd661',
    SUPABASE_URL: process.env.REACT_APP_SUPABASE_URL,
    SUPABASE_ANON_KEY: process.env.REACT_APP_SUPABASE_ANON_KEY
};

export default config; 